/*****************Add country record***************/

Insert into Country (Name,Region_id) Values ('US',100);
Insert into Country (Name,Region_id) Values ('Canada',100);
Insert into Country (Name,Region_id) Values ('Mexico',100);
Insert into Country (Name,Region_id) Values ('Brazil',100);
Insert into Country (Name,Region_id) Values ('Argentina',100);
Insert into Country (Name,Region_id) Values ('Chile',100);
Insert into Country (Name,Region_id) Values ('Uruguay',100);
Insert into Country (Name,Region_id) Values ('England',101);
Insert into Country (Name,Region_id) Values ('Germany',101);
Insert into Country (Name,Region_id) Values ('France',101);
Insert into Country (Name,Region_id) Values ('Spain',101);
Insert into Country (Name,Region_id) Values ('Portugal',101);
Insert into Country (Name,Region_id) Values ('Sweden',101);
Insert into Country (Name,Region_id) Values ('Switzerland',101);
Insert into Country (Name,Region_id) Values ('Norway',101);
Insert into Country (Name,Region_id) Values ('Finland',101);
Insert into Country (Name,Region_id) Values ('Italy',101);
Insert into Country (Name,Region_id) Values ('Russia',101);
Insert into Country (Name,Region_id) Values ('South Africa',102);
Insert into Country (Name,Region_id) Values ('Egypt',102);
Insert into Country (Name,Region_id) Values ('Zimbabwe',102);
Insert into Country (Name,Region_id) Values ('Uganda',102);
Insert into Country (Name,Region_id) Values ('Nigeria',102);
Insert into Country (Name,Region_id) Values ('Kenya',102);
Insert into Country (Name,Region_id) Values ('Ghana',102);
Insert into Country (Name,Region_id) Values ('UAE',103);
Insert into Country (Name,Region_id) Values ('Saudi Arabia',103);
Insert into Country (Name,Region_id) Values ('Qatar',103);
Insert into Country (Name,Region_id) Values ('Jordan',103);
Insert into Country (Name,Region_id) Values ('Iran',103);
Insert into Country (Name,Region_id) Values ('Iraq',103);
Insert into Country (Name,Region_id) Values ('Israel',103);
Insert into Country (Name,Region_id) Values ('Turkey',103);
Insert into Country (Name,Region_id) Values ('Syria',103);
Insert into Country (Name,Region_id) Values ('Afghanistan',103);
Insert into Country (Name,Region_id) Values ('Pakistan',103);
Insert into Country (Name,Region_id) Values ('India',104);
Insert into Country (Name,Region_id) Values ('Sri Lanka',104);
Insert into Country (Name,Region_id) Values ('China',105);
Insert into Country (Name,Region_id) Values ('Nepal',105);
Insert into Country (Name,Region_id) Values ('South Korea',105);
Insert into Country (Name,Region_id) Values ('Japan',105);
Insert into Country (Name,Region_id) Values ('Indonesia',105);
Insert into Country (Name,Region_id) Values ('Singapore',105);
Insert into Country (Name,Region_id) Values ('Hong Kong',105);
Insert into Country (Name,Region_id) Values ('Australia',105);
Insert into Country (Name,Region_id) Values ('NewZealand',105);
Insert into Country (Name,Region_id) Values ('Thailand',105);
Insert into Country (Name,Region_id) Values ('Taiwan',105);